name: ArmiWorldEconomy
version: ${project.version}
main: net.tkdkid1000.armiworld.ArmiWorldEconomy
depend: [FastAsyncWorldEdit, Essentials, LightAPI]
author: TKDKid1000
website: http://tkdkid1000.net
api-version: 1.16
commands:
  house:
    description: Makes a house/teleports to it
    usage: /house
  job:
    description: Job commands
    usage: /job
  thread:
    description: Tries to make a new thread
    usage: /thread
  portal:
    description: Gives portal gun
    usage: /portal
  piano:
    description: Opens piano GUI
    usage: /piano