name: Java CI

on: [push]

jobs:
  build:
    runs-on: tes-computer

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Verify
        run: mvn -B clean verify
